### ISSUE TITLE
use jwt

### ISSUE THREAD

**Issue by Parham-sagharchi** [damien-hl/nuxt3-auth-example#1]
hello,

actually i want to use this template for my project, and i need to use JWT , could help me what should i do to modify this temp according to JWT ?

thanks

**Comment by damien-hl** [comment]
Hello,

I think the easiest way to adapat this template to use JWT is to store the JWT token in a cookie.

I made an example on [this branch](https://github.com/damien-hl/nuxt3-auth-example/tree/jwt) where i used the [jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) package to issue a JWT token and then store it in the cookie.

Check `server/utils/jwt.ts` and `server/api/auth/login.post.ts` files to see how the JWT is created and stored in the cookie.

The online example is here:
https://nuxt3-auth-example-git-jwt-damienhl.vercel.app/

Good luck!
