### ISSUE TITLE
Error: useBody is not defined

### ISSUE THREAD

**Issue by DougHayward** [damien-hl/nuxt3-auth-example#5]
Whilst trying to run this repo I'm hitting the following error when trying to login.

> useBody is not defined

As defined here:

 https://github.com/damien-hl/nuxt3-auth-example/blob/249e47e5aa963f07cb67ee8355024ca9dd3e5039/server/routes/auth/login.post.ts#L6

In order to get the repo to run at all I had to change:

`const cookie = useCookie(event)[config.cookieName]`

To:

`const cookie = getCookie(event, config.cookieName) || 0`

Without this change I get the error:

 > useCookie is not defined

Any pointers would be greatly appreciated. I'm attempting to move from Nuxt 2 to Nuxt 3 and using this repo to replace Nuxt-Auth.

**Comment by damien-hl** [comment]
Hello Doug,

In a recent update, useBody had been renamed to readBody.

```ts
// Old
const body = await useBody<{ email: string; password: string; rememberMe: boolean }>(event)

// New
const body = await readBody<{ email: string; password: string; rememberMe: boolean }>(event)
```

Same applies to useCookie, which has been renamed to getCookie.

Nuxt3 uses some h3 composables for server routes, you can find them [here](https://www.jsdocs.io/package/h3#package-index-functions).

Thank you for pointing this out! I will update the repo soon.
